Add Devise (Authentication)
GhostEsso/Blog_App pull request #9
Opened 2023-11-07 19:59 UTC by GhostEsso

Hello **Code Reviewer🤓**
We hope you're doing well🤗
In this Milestone,
We removed the current_user method in ApplicationController;
We installed and set up devise.
We modified the views in devise for registration and login to match the wireframes from the Sneak Peek and our styling.

The users can:

Register themselves in the app. The application asks for confirmation of the email.
Re-require the email confirmation message.
Confirm their email by clicking on a link in the received email. A hashed password is then stored in the database.
Log in with a combination of email and password.
Reset password.

Thank you for reviewing our PR, Stay blessed :star2:

2023-11-08 10:11 UTC, TedLivist requested changes
## STATUS: CHANGES REQUIRED ♻️ ♻️

Hi @GhostEsso and @chudisoft,

Good job so far!
✔️ Implementation of centered form
However, there are some issues that you still need to work on to go to the next project but you are almost there!

## Required Changes ♻️
_Check the comments under the review._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear. And please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-11-08 10:11 UTC, TedLivist commented on app/models/user.rb
> +         :recoverable, :rememberable, :validatable, :confirmable
- [ ] You have a duplicate devise configuration here. Kindly remove the one on line 4 as it does not have `:confirmable` module, which is required for the project.

2023-11-08 10:11 UTC, TedLivist commented on app/views/devise/registrations/new.html.erb
> +<%= render "devise/shared/links" %>
- [ ] I could not sign up. You are validating for a `name` property but you did not add this in your sign up form, so there's no way to properly sign up in your app.

  ![image](https://github.com/GhostEsso/Blog_App/assets/36542986/1826fa9e-3484-49f3-aecb-291154929665)

- [ ] Since I could not sign up, I could not check other project requirements. Kindly ensure that after signing up users are required to confirm their emails before logging in.

2023-11-08 10:11 UTC, TedLivist commented on app/views/devise/sessions/new.html.erb
> +<%= render "devise/shared/links" %>
- [ ] I could not sign up, so I could not check for the log in functionality. Kindly ensure it works as well.

2023-11-08 10:11 UTC, TedLivist commented on app/views/devise/passwords/new.html.erb
> +<h2>Forgot your password?</h2>
- [ ] Kindly ensue the forgot password functionality works as required too.

2023-11-08 12:49 UTC, julie-ify approved these changes
Hi @GhostEsso and @chudisoft,

## Highlights!
- Good code organization and working devise features ✔️
- Descriptive README ✔️ 

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 

# Status: Approved ✔️ 

Cheers and Happy coding!👏👏👏

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._


Feel free to leave any questions or comments in the PR thread if something is not 100% clear.


------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-11-08 12:50 UTC, merged

2023-11-09 06:35 UTC, shella12 reviewed
Hi @GhostEsso and @chudisoft, 


## Status : APPROVED 🥳 🥳 

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 

<img src="https://media0.giphy.com/media/3kuSo744UIPJjcJUEn/giphy.gif"/>

## Highlights

- Added devise gem ✔️ 
- Authentication is working 👍 
- Implemented all requirements 👏 

## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._